# Generated by Django 4.1.2 on 2022-10-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('Swilang', '0002_translation_created_at_translation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translated_word',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
