# Generated by Django 4.1.2 on 2022-10-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_is_confirmed'),
        ('Swilang', '0003_alter_translation_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='words.word'),
        ),
    ]
