# Generated by Django 4.1.2 on 2022-10-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_is_confirmed'),
        ('languages', '0001_initial'),
        ('Swilang', '0007_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('word', 'language')},
        ),
    ]
