# Generated by Django 4.1.2 on 2023-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swilang', '0008_alter_translation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
