# Generated by Django 4.1.2 on 2023-04-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swilang', '0009_report_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='auto_translated',
            field=models.BooleanField(default=False),
        ),
    ]
