# Generated by Django 4.1.2 on 2022-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
                ('language_short', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
